model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: ВАШ_КЛЮЧ
      api_base: https://ваш-альтернативный-api.com/v1

  # Ollama (локально)
  # - model_name: deepseek-r1:1.5b
  #   litellm_params:
  #     model: ollama/deepseek-r1:1.5b
  #     api_base: http://host.docker.internal:11434