model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: ВАШ_КЛЮЧ
      api_base: https://ваш-альтернативный-api.com/v1

  # Ollama (локально)
  # - model_name: llama3
  #   litellm_params:
  #     model: ollama/llama3
  #     api_base: http://host.docker.internal:11434

  # - model_name: phi3
  #   litellm_params:
  #     model: ollama/phi3
  #     api_base: http://host.docker.internal:11434