model_list:
  # Ollama (локально)
  - model_name: deepseek-r1:1.5b
    litellm_params:
      model: ollama/deepseek-r1:1.5b
      api_base: http://localhost:11434

  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: __HYDRA_API_KEY__
      api_base: __HYDRA_API_BASE__