version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped

  litellm:
    image: litellm/serve:latest
    ports:
      - "8003:8003"
    volumes:
      - ./litellm/config.yaml:/app/config.yaml
    environment:
      - CONFIG_PATH=/app/config.yaml
    command: ["--config", "/app/config.yaml"]
    depends_on:
      - ollama
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:lite
    ports:
      - "3002:8080"
    volumes:
      - open_webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://none
      - OPENAI_API_BASE_URL=http://litellm:8003
      - OPENAI_API_KEY=any
    depends_on:
      - litellm
    restart: unless-stopped

volumes:
  ollama_data:
  open_webui_data: