FROM python:3.10-slim

# Установка envsubst (входит в gettext)
RUN apt-get update && apt-get install -y gettext && rm -rf /var/lib/apt/lists/*

# Установка зависимостей
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --user -r /app/requirements.txt

# Переменная PATH
ENV PATH="/root/.local/bin:${PATH}"

# Рабочая директория
WORKDIR /app

# Копируем файлы
COPY config.yaml.tpl /app/config.yaml.tpl
COPY entrypoint.sh /app/entrypoint.sh

# Порт
EXPOSE 8003

# Запуск
ENTRYPOINT ["/app/entrypoint.sh"]