model_list:
  # Ollama (локально)
  - model_name: deepseek-r1:1.5b
    litellm_params:
      model: ollama/deepseek-r1:1.5b
      api_base: http://localhost:11434

  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: ${HYDRA_API_KEY}
      api_base: ${HYDRA_API_BASE}